-- Baseline: snapshot do schema ja existente no banco de desenvolvimento, na
-- data em que o projeto passou a usar Flyway. Bancos ja existentes usam
-- spring.flyway.baseline-on-migrate=true e nao reexecutam este script;
-- bancos novos/vazios (ex.: CI, ambiente de um novo desenvolvedor) o executam
-- para chegar ao mesmo estado.
--
-- cliente.cpf, cliente.cidade e cliente.data_cadastro sao colunas legadas de
-- uma versao anterior do projeto e nao sao mapeadas pela entidade Cliente
-- atual; foram mantidas aqui para refletir fielmente o schema real, mas nao
-- sao usadas pela aplicacao.

CREATE TABLE artista (
    id_artista bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255),
    descricao character varying(255),
    email character varying(255),
    senha character varying(255),
    tipo_usuario character varying(255)
);

CREATE TABLE cliente (
    id_cliente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    senha character varying(255),
    telefone character varying(255),
    tipo_usuario character varying(255),
    cpf character varying(14) UNIQUE,
    cidade character varying(50),
    data_cadastro date NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE servico (
    id_servico bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_artista bigint,
    titulo character varying(255),
    descricao character varying(255),
    valor_servico double precision
);

CREATE TABLE portfolio (
    id_portfolio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_artista bigint,
    titulo character varying(255),
    descricao character varying(255),
    imagem_url character varying(255),
    id_cliente bigint,
    id_pedido bigint
);

CREATE TABLE pedido (
    id_pedido bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente bigint,
    id_artista bigint,
    id_servico bigint,
    id_arte bigint,
    descricao character varying(255),
    dt_pedido timestamp(6) without time zone,
    dt_previsao_entrega timestamp(6) without time zone,
    entregue boolean,
    trabalhando boolean,
    id_portfolio bigint,
    imagem_url character varying(255)
);

CREATE TABLE arte (
    id_arte bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_portfolio bigint,
    titulo character varying(255),
    descricao character varying(255),
    vote bigint
);
